[package]
name = "Rails"
edition = "2024.beta"
version = "0.1.0"

[dependencies]
Sui = { local = "/Users/mac/.move/git/https___github_com_MystenLabs_sui_git_2f5992f189cd24445cd010ccf0aa7ff418ff93b1/crates/sui-framework/packages/sui-framework" }

[addresses]
rails = "0x0"

[dev-addresses]
rails = "0x0"
