blank_issues_enabled: false
contact_links:
  - name: "Rails Dev Community"
    url: "https://t.me/+Stx-wLOdj49iNDM0"
    about: "Please ask and answer questions here."
  - name: "Rails Security Bug Bounty"
    url: "engineering@usezoracle.com"
    about: "Please report security vulnerabilities here."
