// Code generated by ent, DO NOT EDIT.

package routeaevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/usezoracle/rails-sui/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldLTE(FieldID, id))
}

// At applies equality check predicate on the "at" field. It's identical to AtEQ.
func At(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldAt, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldDurationMs, v))
}

// ErrorMsg applies equality check predicate on the "error_msg" field. It's identical to ErrorMsgEQ.
func ErrorMsg(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldErrorMsg, v))
}

// CorrelationID applies equality check predicate on the "correlation_id" field. It's identical to CorrelationIDEQ.
func CorrelationID(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldCorrelationID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// StepEQ applies the EQ predicate on the "step" field.
func StepEQ(v Step) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldStep, v))
}

// StepNEQ applies the NEQ predicate on the "step" field.
func StepNEQ(v Step) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNEQ(FieldStep, v))
}

// StepIn applies the In predicate on the "step" field.
func StepIn(vs ...Step) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIn(FieldStep, vs...))
}

// StepNotIn applies the NotIn predicate on the "step" field.
func StepNotIn(vs ...Step) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotIn(FieldStep, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// ActorEQ applies the EQ predicate on the "actor" field.
func ActorEQ(v Actor) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldActor, v))
}

// ActorNEQ applies the NEQ predicate on the "actor" field.
func ActorNEQ(v Actor) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNEQ(FieldActor, v))
}

// ActorIn applies the In predicate on the "actor" field.
func ActorIn(vs ...Actor) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIn(FieldActor, vs...))
}

// ActorNotIn applies the NotIn predicate on the "actor" field.
func ActorNotIn(vs ...Actor) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotIn(FieldActor, vs...))
}

// AtEQ applies the EQ predicate on the "at" field.
func AtEQ(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldAt, v))
}

// AtNEQ applies the NEQ predicate on the "at" field.
func AtNEQ(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNEQ(FieldAt, v))
}

// AtIn applies the In predicate on the "at" field.
func AtIn(vs ...time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIn(FieldAt, vs...))
}

// AtNotIn applies the NotIn predicate on the "at" field.
func AtNotIn(vs ...time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotIn(FieldAt, vs...))
}

// AtGT applies the GT predicate on the "at" field.
func AtGT(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldGT(FieldAt, v))
}

// AtGTE applies the GTE predicate on the "at" field.
func AtGTE(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldGTE(FieldAt, v))
}

// AtLT applies the LT predicate on the "at" field.
func AtLT(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldLT(FieldAt, v))
}

// AtLTE applies the LTE predicate on the "at" field.
func AtLTE(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldLTE(FieldAt, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotNull(FieldDurationMs))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotNull(FieldPayload))
}

// ErrorMsgEQ applies the EQ predicate on the "error_msg" field.
func ErrorMsgEQ(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldErrorMsg, v))
}

// ErrorMsgNEQ applies the NEQ predicate on the "error_msg" field.
func ErrorMsgNEQ(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNEQ(FieldErrorMsg, v))
}

// ErrorMsgIn applies the In predicate on the "error_msg" field.
func ErrorMsgIn(vs ...string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIn(FieldErrorMsg, vs...))
}

// ErrorMsgNotIn applies the NotIn predicate on the "error_msg" field.
func ErrorMsgNotIn(vs ...string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotIn(FieldErrorMsg, vs...))
}

// ErrorMsgGT applies the GT predicate on the "error_msg" field.
func ErrorMsgGT(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldGT(FieldErrorMsg, v))
}

// ErrorMsgGTE applies the GTE predicate on the "error_msg" field.
func ErrorMsgGTE(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldGTE(FieldErrorMsg, v))
}

// ErrorMsgLT applies the LT predicate on the "error_msg" field.
func ErrorMsgLT(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldLT(FieldErrorMsg, v))
}

// ErrorMsgLTE applies the LTE predicate on the "error_msg" field.
func ErrorMsgLTE(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldLTE(FieldErrorMsg, v))
}

// ErrorMsgContains applies the Contains predicate on the "error_msg" field.
func ErrorMsgContains(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldContains(FieldErrorMsg, v))
}

// ErrorMsgHasPrefix applies the HasPrefix predicate on the "error_msg" field.
func ErrorMsgHasPrefix(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldHasPrefix(FieldErrorMsg, v))
}

// ErrorMsgHasSuffix applies the HasSuffix predicate on the "error_msg" field.
func ErrorMsgHasSuffix(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldHasSuffix(FieldErrorMsg, v))
}

// ErrorMsgIsNil applies the IsNil predicate on the "error_msg" field.
func ErrorMsgIsNil() predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIsNull(FieldErrorMsg))
}

// ErrorMsgNotNil applies the NotNil predicate on the "error_msg" field.
func ErrorMsgNotNil() predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotNull(FieldErrorMsg))
}

// ErrorMsgEqualFold applies the EqualFold predicate on the "error_msg" field.
func ErrorMsgEqualFold(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEqualFold(FieldErrorMsg, v))
}

// ErrorMsgContainsFold applies the ContainsFold predicate on the "error_msg" field.
func ErrorMsgContainsFold(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldContainsFold(FieldErrorMsg, v))
}

// CorrelationIDEQ applies the EQ predicate on the "correlation_id" field.
func CorrelationIDEQ(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldCorrelationID, v))
}

// CorrelationIDNEQ applies the NEQ predicate on the "correlation_id" field.
func CorrelationIDNEQ(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNEQ(FieldCorrelationID, v))
}

// CorrelationIDIn applies the In predicate on the "correlation_id" field.
func CorrelationIDIn(vs ...string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIn(FieldCorrelationID, vs...))
}

// CorrelationIDNotIn applies the NotIn predicate on the "correlation_id" field.
func CorrelationIDNotIn(vs ...string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotIn(FieldCorrelationID, vs...))
}

// CorrelationIDGT applies the GT predicate on the "correlation_id" field.
func CorrelationIDGT(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldGT(FieldCorrelationID, v))
}

// CorrelationIDGTE applies the GTE predicate on the "correlation_id" field.
func CorrelationIDGTE(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldGTE(FieldCorrelationID, v))
}

// CorrelationIDLT applies the LT predicate on the "correlation_id" field.
func CorrelationIDLT(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldLT(FieldCorrelationID, v))
}

// CorrelationIDLTE applies the LTE predicate on the "correlation_id" field.
func CorrelationIDLTE(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldLTE(FieldCorrelationID, v))
}

// CorrelationIDContains applies the Contains predicate on the "correlation_id" field.
func CorrelationIDContains(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldContains(FieldCorrelationID, v))
}

// CorrelationIDHasPrefix applies the HasPrefix predicate on the "correlation_id" field.
func CorrelationIDHasPrefix(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldHasPrefix(FieldCorrelationID, v))
}

// CorrelationIDHasSuffix applies the HasSuffix predicate on the "correlation_id" field.
func CorrelationIDHasSuffix(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldHasSuffix(FieldCorrelationID, v))
}

// CorrelationIDIsNil applies the IsNil predicate on the "correlation_id" field.
func CorrelationIDIsNil() predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIsNull(FieldCorrelationID))
}

// CorrelationIDNotNil applies the NotNil predicate on the "correlation_id" field.
func CorrelationIDNotNil() predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotNull(FieldCorrelationID))
}

// CorrelationIDEqualFold applies the EqualFold predicate on the "correlation_id" field.
func CorrelationIDEqualFold(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEqualFold(FieldCorrelationID, v))
}

// CorrelationIDContainsFold applies the ContainsFold predicate on the "correlation_id" field.
func CorrelationIDContainsFold(v string) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldContainsFold(FieldCorrelationID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// HasRouteAOrder applies the HasEdge predicate on the "route_a_order" edge.
func HasRouteAOrder() predicate.RouteAEvent {
	return predicate.RouteAEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RouteAOrderTable, RouteAOrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRouteAOrderWith applies the HasEdge predicate on the "route_a_order" edge with a given conditions (other predicates).
func HasRouteAOrderWith(preds ...predicate.RouteAOrder) predicate.RouteAEvent {
	return predicate.RouteAEvent(func(s *sql.Selector) {
		step := newRouteAOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RouteAEvent) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RouteAEvent) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RouteAEvent) predicate.RouteAEvent {
	return predicate.RouteAEvent(sql.NotPredicates(p))
}
