// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/usezoracle/rails-sui/ent/adminauditlog"
	"github.com/usezoracle/rails-sui/ent/predicate"
)

// AdminAuditLogUpdate is the builder for updating AdminAuditLog entities.
type AdminAuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AdminAuditLogMutation
}

// Where appends a list predicates to the AdminAuditLogUpdate builder.
func (aalu *AdminAuditLogUpdate) Where(ps ...predicate.AdminAuditLog) *AdminAuditLogUpdate {
	aalu.mutation.Where(ps...)
	return aalu
}

// SetDetail sets the "detail" field.
func (aalu *AdminAuditLogUpdate) SetDetail(m map[string]interface{}) *AdminAuditLogUpdate {
	aalu.mutation.SetDetail(m)
	return aalu
}

// ClearDetail clears the value of the "detail" field.
func (aalu *AdminAuditLogUpdate) ClearDetail() *AdminAuditLogUpdate {
	aalu.mutation.ClearDetail()
	return aalu
}

// Mutation returns the AdminAuditLogMutation object of the builder.
func (aalu *AdminAuditLogUpdate) Mutation() *AdminAuditLogMutation {
	return aalu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aalu *AdminAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, aalu.sqlSave, aalu.mutation, aalu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aalu *AdminAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := aalu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aalu *AdminAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := aalu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aalu *AdminAuditLogUpdate) ExecX(ctx context.Context) {
	if err := aalu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (aalu *AdminAuditLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminauditlog.Table, adminauditlog.Columns, sqlgraph.NewFieldSpec(adminauditlog.FieldID, field.TypeUUID))
	if ps := aalu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if aalu.mutation.TargetCleared() {
		_spec.ClearField(adminauditlog.FieldTarget, field.TypeString)
	}
	if value, ok := aalu.mutation.Detail(); ok {
		_spec.SetField(adminauditlog.FieldDetail, field.TypeJSON, value)
	}
	if aalu.mutation.DetailCleared() {
		_spec.ClearField(adminauditlog.FieldDetail, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aalu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aalu.mutation.done = true
	return n, nil
}

// AdminAuditLogUpdateOne is the builder for updating a single AdminAuditLog entity.
type AdminAuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminAuditLogMutation
}

// SetDetail sets the "detail" field.
func (aaluo *AdminAuditLogUpdateOne) SetDetail(m map[string]interface{}) *AdminAuditLogUpdateOne {
	aaluo.mutation.SetDetail(m)
	return aaluo
}

// ClearDetail clears the value of the "detail" field.
func (aaluo *AdminAuditLogUpdateOne) ClearDetail() *AdminAuditLogUpdateOne {
	aaluo.mutation.ClearDetail()
	return aaluo
}

// Mutation returns the AdminAuditLogMutation object of the builder.
func (aaluo *AdminAuditLogUpdateOne) Mutation() *AdminAuditLogMutation {
	return aaluo.mutation
}

// Where appends a list predicates to the AdminAuditLogUpdate builder.
func (aaluo *AdminAuditLogUpdateOne) Where(ps ...predicate.AdminAuditLog) *AdminAuditLogUpdateOne {
	aaluo.mutation.Where(ps...)
	return aaluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aaluo *AdminAuditLogUpdateOne) Select(field string, fields ...string) *AdminAuditLogUpdateOne {
	aaluo.fields = append([]string{field}, fields...)
	return aaluo
}

// Save executes the query and returns the updated AdminAuditLog entity.
func (aaluo *AdminAuditLogUpdateOne) Save(ctx context.Context) (*AdminAuditLog, error) {
	return withHooks(ctx, aaluo.sqlSave, aaluo.mutation, aaluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aaluo *AdminAuditLogUpdateOne) SaveX(ctx context.Context) *AdminAuditLog {
	node, err := aaluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aaluo *AdminAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := aaluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aaluo *AdminAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := aaluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (aaluo *AdminAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AdminAuditLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminauditlog.Table, adminauditlog.Columns, sqlgraph.NewFieldSpec(adminauditlog.FieldID, field.TypeUUID))
	id, ok := aaluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aaluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminauditlog.FieldID)
		for _, f := range fields {
			if !adminauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aaluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if aaluo.mutation.TargetCleared() {
		_spec.ClearField(adminauditlog.FieldTarget, field.TypeString)
	}
	if value, ok := aaluo.mutation.Detail(); ok {
		_spec.SetField(adminauditlog.FieldDetail, field.TypeJSON, value)
	}
	if aaluo.mutation.DetailCleared() {
		_spec.ClearField(adminauditlog.FieldDetail, field.TypeJSON)
	}
	_node = &AdminAuditLog{config: aaluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aaluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aaluo.mutation.done = true
	return _node, nil
}
