// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/usezoracle/rails-sui/ent/cardservernonce"
	"github.com/usezoracle/rails-sui/ent/senderprofile"
	"github.com/usezoracle/rails-sui/ent/tappcard"
)

// CardServerNonce is the model entity for the CardServerNonce schema.
type CardServerNonce struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Nonce holds the value of the "nonce" field.
	Nonce []byte `json:"nonce,omitempty"`
	// Tier holds the value of the "tier" field.
	Tier cardservernonce.Tier `json:"tier,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount string `json:"amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt *time.Time `json:"consumed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CardServerNonceQuery when eager-loading is set.
	Edges                             CardServerNonceEdges `json:"edges"`
	sender_profile_card_server_nonces *uuid.UUID
	tapp_card_server_nonces           *uuid.UUID
	selectValues                      sql.SelectValues
}

// CardServerNonceEdges holds the relations/edges for other nodes in the graph.
type CardServerNonceEdges struct {
	// Card holds the value of the card edge.
	Card *TappCard `json:"card,omitempty"`
	// SenderProfile holds the value of the sender_profile edge.
	SenderProfile *SenderProfile `json:"sender_profile,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CardOrErr returns the Card value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CardServerNonceEdges) CardOrErr() (*TappCard, error) {
	if e.Card != nil {
		return e.Card, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tappcard.Label}
	}
	return nil, &NotLoadedError{edge: "card"}
}

// SenderProfileOrErr returns the SenderProfile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CardServerNonceEdges) SenderProfileOrErr() (*SenderProfile, error) {
	if e.SenderProfile != nil {
		return e.SenderProfile, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: senderprofile.Label}
	}
	return nil, &NotLoadedError{edge: "sender_profile"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CardServerNonce) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cardservernonce.FieldNonce:
			values[i] = new([]byte)
		case cardservernonce.FieldTier, cardservernonce.FieldAmount, cardservernonce.FieldCurrency:
			values[i] = new(sql.NullString)
		case cardservernonce.FieldCreatedAt, cardservernonce.FieldUpdatedAt, cardservernonce.FieldExpiresAt, cardservernonce.FieldConsumedAt:
			values[i] = new(sql.NullTime)
		case cardservernonce.FieldID:
			values[i] = new(uuid.UUID)
		case cardservernonce.ForeignKeys[0]: // sender_profile_card_server_nonces
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case cardservernonce.ForeignKeys[1]: // tapp_card_server_nonces
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CardServerNonce fields.
func (csn *CardServerNonce) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cardservernonce.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				csn.ID = *value
			}
		case cardservernonce.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				csn.CreatedAt = value.Time
			}
		case cardservernonce.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				csn.UpdatedAt = value.Time
			}
		case cardservernonce.FieldNonce:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field nonce", values[i])
			} else if value != nil {
				csn.Nonce = *value
			}
		case cardservernonce.FieldTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tier", values[i])
			} else if value.Valid {
				csn.Tier = cardservernonce.Tier(value.String)
			}
		case cardservernonce.FieldAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				csn.Amount = value.String
			}
		case cardservernonce.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				csn.Currency = value.String
			}
		case cardservernonce.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				csn.ExpiresAt = value.Time
			}
		case cardservernonce.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				csn.ConsumedAt = new(time.Time)
				*csn.ConsumedAt = value.Time
			}
		case cardservernonce.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field sender_profile_card_server_nonces", values[i])
			} else if value.Valid {
				csn.sender_profile_card_server_nonces = new(uuid.UUID)
				*csn.sender_profile_card_server_nonces = *value.S.(*uuid.UUID)
			}
		case cardservernonce.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field tapp_card_server_nonces", values[i])
			} else if value.Valid {
				csn.tapp_card_server_nonces = new(uuid.UUID)
				*csn.tapp_card_server_nonces = *value.S.(*uuid.UUID)
			}
		default:
			csn.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CardServerNonce.
// This includes values selected through modifiers, order, etc.
func (csn *CardServerNonce) Value(name string) (ent.Value, error) {
	return csn.selectValues.Get(name)
}

// QueryCard queries the "card" edge of the CardServerNonce entity.
func (csn *CardServerNonce) QueryCard() *TappCardQuery {
	return NewCardServerNonceClient(csn.config).QueryCard(csn)
}

// QuerySenderProfile queries the "sender_profile" edge of the CardServerNonce entity.
func (csn *CardServerNonce) QuerySenderProfile() *SenderProfileQuery {
	return NewCardServerNonceClient(csn.config).QuerySenderProfile(csn)
}

// Update returns a builder for updating this CardServerNonce.
// Note that you need to call CardServerNonce.Unwrap() before calling this method if this CardServerNonce
// was returned from a transaction, and the transaction was committed or rolled back.
func (csn *CardServerNonce) Update() *CardServerNonceUpdateOne {
	return NewCardServerNonceClient(csn.config).UpdateOne(csn)
}

// Unwrap unwraps the CardServerNonce entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (csn *CardServerNonce) Unwrap() *CardServerNonce {
	_tx, ok := csn.config.driver.(*txDriver)
	if !ok {
		panic("ent: CardServerNonce is not a transactional entity")
	}
	csn.config.driver = _tx.drv
	return csn
}

// String implements the fmt.Stringer.
func (csn *CardServerNonce) String() string {
	var builder strings.Builder
	builder.WriteString("CardServerNonce(")
	builder.WriteString(fmt.Sprintf("id=%v, ", csn.ID))
	builder.WriteString("created_at=")
	builder.WriteString(csn.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(csn.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("nonce=")
	builder.WriteString(fmt.Sprintf("%v", csn.Nonce))
	builder.WriteString(", ")
	builder.WriteString("tier=")
	builder.WriteString(fmt.Sprintf("%v", csn.Tier))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(csn.Amount)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(csn.Currency)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(csn.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := csn.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CardServerNonces is a parsable slice of CardServerNonce.
type CardServerNonces []*CardServerNonce
