// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/usezoracle/rails-sui/ent/cardservernonce"
	"github.com/usezoracle/rails-sui/ent/senderprofile"
	"github.com/usezoracle/rails-sui/ent/tappcard"
)

// CardServerNonceCreate is the builder for creating a CardServerNonce entity.
type CardServerNonceCreate struct {
	config
	mutation *CardServerNonceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (csnc *CardServerNonceCreate) SetCreatedAt(t time.Time) *CardServerNonceCreate {
	csnc.mutation.SetCreatedAt(t)
	return csnc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (csnc *CardServerNonceCreate) SetNillableCreatedAt(t *time.Time) *CardServerNonceCreate {
	if t != nil {
		csnc.SetCreatedAt(*t)
	}
	return csnc
}

// SetUpdatedAt sets the "updated_at" field.
func (csnc *CardServerNonceCreate) SetUpdatedAt(t time.Time) *CardServerNonceCreate {
	csnc.mutation.SetUpdatedAt(t)
	return csnc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (csnc *CardServerNonceCreate) SetNillableUpdatedAt(t *time.Time) *CardServerNonceCreate {
	if t != nil {
		csnc.SetUpdatedAt(*t)
	}
	return csnc
}

// SetNonce sets the "nonce" field.
func (csnc *CardServerNonceCreate) SetNonce(b []byte) *CardServerNonceCreate {
	csnc.mutation.SetNonce(b)
	return csnc
}

// SetTier sets the "tier" field.
func (csnc *CardServerNonceCreate) SetTier(c cardservernonce.Tier) *CardServerNonceCreate {
	csnc.mutation.SetTier(c)
	return csnc
}

// SetAmount sets the "amount" field.
func (csnc *CardServerNonceCreate) SetAmount(s string) *CardServerNonceCreate {
	csnc.mutation.SetAmount(s)
	return csnc
}

// SetCurrency sets the "currency" field.
func (csnc *CardServerNonceCreate) SetCurrency(s string) *CardServerNonceCreate {
	csnc.mutation.SetCurrency(s)
	return csnc
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (csnc *CardServerNonceCreate) SetNillableCurrency(s *string) *CardServerNonceCreate {
	if s != nil {
		csnc.SetCurrency(*s)
	}
	return csnc
}

// SetExpiresAt sets the "expires_at" field.
func (csnc *CardServerNonceCreate) SetExpiresAt(t time.Time) *CardServerNonceCreate {
	csnc.mutation.SetExpiresAt(t)
	return csnc
}

// SetConsumedAt sets the "consumed_at" field.
func (csnc *CardServerNonceCreate) SetConsumedAt(t time.Time) *CardServerNonceCreate {
	csnc.mutation.SetConsumedAt(t)
	return csnc
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (csnc *CardServerNonceCreate) SetNillableConsumedAt(t *time.Time) *CardServerNonceCreate {
	if t != nil {
		csnc.SetConsumedAt(*t)
	}
	return csnc
}

// SetID sets the "id" field.
func (csnc *CardServerNonceCreate) SetID(u uuid.UUID) *CardServerNonceCreate {
	csnc.mutation.SetID(u)
	return csnc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (csnc *CardServerNonceCreate) SetNillableID(u *uuid.UUID) *CardServerNonceCreate {
	if u != nil {
		csnc.SetID(*u)
	}
	return csnc
}

// SetCardID sets the "card" edge to the TappCard entity by ID.
func (csnc *CardServerNonceCreate) SetCardID(id uuid.UUID) *CardServerNonceCreate {
	csnc.mutation.SetCardID(id)
	return csnc
}

// SetCard sets the "card" edge to the TappCard entity.
func (csnc *CardServerNonceCreate) SetCard(t *TappCard) *CardServerNonceCreate {
	return csnc.SetCardID(t.ID)
}

// SetSenderProfileID sets the "sender_profile" edge to the SenderProfile entity by ID.
func (csnc *CardServerNonceCreate) SetSenderProfileID(id uuid.UUID) *CardServerNonceCreate {
	csnc.mutation.SetSenderProfileID(id)
	return csnc
}

// SetSenderProfile sets the "sender_profile" edge to the SenderProfile entity.
func (csnc *CardServerNonceCreate) SetSenderProfile(s *SenderProfile) *CardServerNonceCreate {
	return csnc.SetSenderProfileID(s.ID)
}

// Mutation returns the CardServerNonceMutation object of the builder.
func (csnc *CardServerNonceCreate) Mutation() *CardServerNonceMutation {
	return csnc.mutation
}

// Save creates the CardServerNonce in the database.
func (csnc *CardServerNonceCreate) Save(ctx context.Context) (*CardServerNonce, error) {
	csnc.defaults()
	return withHooks(ctx, csnc.sqlSave, csnc.mutation, csnc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (csnc *CardServerNonceCreate) SaveX(ctx context.Context) *CardServerNonce {
	v, err := csnc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (csnc *CardServerNonceCreate) Exec(ctx context.Context) error {
	_, err := csnc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csnc *CardServerNonceCreate) ExecX(ctx context.Context) {
	if err := csnc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (csnc *CardServerNonceCreate) defaults() {
	if _, ok := csnc.mutation.CreatedAt(); !ok {
		v := cardservernonce.DefaultCreatedAt()
		csnc.mutation.SetCreatedAt(v)
	}
	if _, ok := csnc.mutation.UpdatedAt(); !ok {
		v := cardservernonce.DefaultUpdatedAt()
		csnc.mutation.SetUpdatedAt(v)
	}
	if _, ok := csnc.mutation.Currency(); !ok {
		v := cardservernonce.DefaultCurrency
		csnc.mutation.SetCurrency(v)
	}
	if _, ok := csnc.mutation.ID(); !ok {
		v := cardservernonce.DefaultID()
		csnc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (csnc *CardServerNonceCreate) check() error {
	if _, ok := csnc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CardServerNonce.created_at"`)}
	}
	if _, ok := csnc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CardServerNonce.updated_at"`)}
	}
	if _, ok := csnc.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`ent: missing required field "CardServerNonce.nonce"`)}
	}
	if v, ok := csnc.mutation.Nonce(); ok {
		if err := cardservernonce.NonceValidator(v); err != nil {
			return &ValidationError{Name: "nonce", err: fmt.Errorf(`ent: validator failed for field "CardServerNonce.nonce": %w`, err)}
		}
	}
	if _, ok := csnc.mutation.Tier(); !ok {
		return &ValidationError{Name: "tier", err: errors.New(`ent: missing required field "CardServerNonce.tier"`)}
	}
	if v, ok := csnc.mutation.Tier(); ok {
		if err := cardservernonce.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "CardServerNonce.tier": %w`, err)}
		}
	}
	if _, ok := csnc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "CardServerNonce.amount"`)}
	}
	if v, ok := csnc.mutation.Amount(); ok {
		if err := cardservernonce.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "CardServerNonce.amount": %w`, err)}
		}
	}
	if _, ok := csnc.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "CardServerNonce.currency"`)}
	}
	if v, ok := csnc.mutation.Currency(); ok {
		if err := cardservernonce.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CardServerNonce.currency": %w`, err)}
		}
	}
	if _, ok := csnc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "CardServerNonce.expires_at"`)}
	}
	if len(csnc.mutation.CardIDs()) == 0 {
		return &ValidationError{Name: "card", err: errors.New(`ent: missing required edge "CardServerNonce.card"`)}
	}
	if len(csnc.mutation.SenderProfileIDs()) == 0 {
		return &ValidationError{Name: "sender_profile", err: errors.New(`ent: missing required edge "CardServerNonce.sender_profile"`)}
	}
	return nil
}

func (csnc *CardServerNonceCreate) sqlSave(ctx context.Context) (*CardServerNonce, error) {
	if err := csnc.check(); err != nil {
		return nil, err
	}
	_node, _spec := csnc.createSpec()
	if err := sqlgraph.CreateNode(ctx, csnc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	csnc.mutation.id = &_node.ID
	csnc.mutation.done = true
	return _node, nil
}

func (csnc *CardServerNonceCreate) createSpec() (*CardServerNonce, *sqlgraph.CreateSpec) {
	var (
		_node = &CardServerNonce{config: csnc.config}
		_spec = sqlgraph.NewCreateSpec(cardservernonce.Table, sqlgraph.NewFieldSpec(cardservernonce.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = csnc.conflict
	if id, ok := csnc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := csnc.mutation.CreatedAt(); ok {
		_spec.SetField(cardservernonce.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := csnc.mutation.UpdatedAt(); ok {
		_spec.SetField(cardservernonce.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := csnc.mutation.Nonce(); ok {
		_spec.SetField(cardservernonce.FieldNonce, field.TypeBytes, value)
		_node.Nonce = value
	}
	if value, ok := csnc.mutation.Tier(); ok {
		_spec.SetField(cardservernonce.FieldTier, field.TypeEnum, value)
		_node.Tier = value
	}
	if value, ok := csnc.mutation.Amount(); ok {
		_spec.SetField(cardservernonce.FieldAmount, field.TypeString, value)
		_node.Amount = value
	}
	if value, ok := csnc.mutation.Currency(); ok {
		_spec.SetField(cardservernonce.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := csnc.mutation.ExpiresAt(); ok {
		_spec.SetField(cardservernonce.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := csnc.mutation.ConsumedAt(); ok {
		_spec.SetField(cardservernonce.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if nodes := csnc.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardservernonce.CardTable,
			Columns: []string{cardservernonce.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tappcard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tapp_card_server_nonces = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := csnc.mutation.SenderProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardservernonce.SenderProfileTable,
			Columns: []string{cardservernonce.SenderProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(senderprofile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.sender_profile_card_server_nonces = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CardServerNonce.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CardServerNonceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (csnc *CardServerNonceCreate) OnConflict(opts ...sql.ConflictOption) *CardServerNonceUpsertOne {
	csnc.conflict = opts
	return &CardServerNonceUpsertOne{
		create: csnc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CardServerNonce.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (csnc *CardServerNonceCreate) OnConflictColumns(columns ...string) *CardServerNonceUpsertOne {
	csnc.conflict = append(csnc.conflict, sql.ConflictColumns(columns...))
	return &CardServerNonceUpsertOne{
		create: csnc,
	}
}

type (
	// CardServerNonceUpsertOne is the builder for "upsert"-ing
	//  one CardServerNonce node.
	CardServerNonceUpsertOne struct {
		create *CardServerNonceCreate
	}

	// CardServerNonceUpsert is the "OnConflict" setter.
	CardServerNonceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CardServerNonceUpsert) SetUpdatedAt(v time.Time) *CardServerNonceUpsert {
	u.Set(cardservernonce.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CardServerNonceUpsert) UpdateUpdatedAt() *CardServerNonceUpsert {
	u.SetExcluded(cardservernonce.FieldUpdatedAt)
	return u
}

// SetNonce sets the "nonce" field.
func (u *CardServerNonceUpsert) SetNonce(v []byte) *CardServerNonceUpsert {
	u.Set(cardservernonce.FieldNonce, v)
	return u
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *CardServerNonceUpsert) UpdateNonce() *CardServerNonceUpsert {
	u.SetExcluded(cardservernonce.FieldNonce)
	return u
}

// SetTier sets the "tier" field.
func (u *CardServerNonceUpsert) SetTier(v cardservernonce.Tier) *CardServerNonceUpsert {
	u.Set(cardservernonce.FieldTier, v)
	return u
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *CardServerNonceUpsert) UpdateTier() *CardServerNonceUpsert {
	u.SetExcluded(cardservernonce.FieldTier)
	return u
}

// SetAmount sets the "amount" field.
func (u *CardServerNonceUpsert) SetAmount(v string) *CardServerNonceUpsert {
	u.Set(cardservernonce.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CardServerNonceUpsert) UpdateAmount() *CardServerNonceUpsert {
	u.SetExcluded(cardservernonce.FieldAmount)
	return u
}

// SetCurrency sets the "currency" field.
func (u *CardServerNonceUpsert) SetCurrency(v string) *CardServerNonceUpsert {
	u.Set(cardservernonce.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CardServerNonceUpsert) UpdateCurrency() *CardServerNonceUpsert {
	u.SetExcluded(cardservernonce.FieldCurrency)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *CardServerNonceUpsert) SetExpiresAt(v time.Time) *CardServerNonceUpsert {
	u.Set(cardservernonce.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CardServerNonceUpsert) UpdateExpiresAt() *CardServerNonceUpsert {
	u.SetExcluded(cardservernonce.FieldExpiresAt)
	return u
}

// SetConsumedAt sets the "consumed_at" field.
func (u *CardServerNonceUpsert) SetConsumedAt(v time.Time) *CardServerNonceUpsert {
	u.Set(cardservernonce.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *CardServerNonceUpsert) UpdateConsumedAt() *CardServerNonceUpsert {
	u.SetExcluded(cardservernonce.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *CardServerNonceUpsert) ClearConsumedAt() *CardServerNonceUpsert {
	u.SetNull(cardservernonce.FieldConsumedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CardServerNonce.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(cardservernonce.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CardServerNonceUpsertOne) UpdateNewValues() *CardServerNonceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(cardservernonce.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(cardservernonce.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CardServerNonce.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CardServerNonceUpsertOne) Ignore() *CardServerNonceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CardServerNonceUpsertOne) DoNothing() *CardServerNonceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CardServerNonceCreate.OnConflict
// documentation for more info.
func (u *CardServerNonceUpsertOne) Update(set func(*CardServerNonceUpsert)) *CardServerNonceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CardServerNonceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CardServerNonceUpsertOne) SetUpdatedAt(v time.Time) *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CardServerNonceUpsertOne) UpdateUpdatedAt() *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetNonce sets the "nonce" field.
func (u *CardServerNonceUpsertOne) SetNonce(v []byte) *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *CardServerNonceUpsertOne) UpdateNonce() *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateNonce()
	})
}

// SetTier sets the "tier" field.
func (u *CardServerNonceUpsertOne) SetTier(v cardservernonce.Tier) *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *CardServerNonceUpsertOne) UpdateTier() *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateTier()
	})
}

// SetAmount sets the "amount" field.
func (u *CardServerNonceUpsertOne) SetAmount(v string) *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CardServerNonceUpsertOne) UpdateAmount() *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *CardServerNonceUpsertOne) SetCurrency(v string) *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CardServerNonceUpsertOne) UpdateCurrency() *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateCurrency()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CardServerNonceUpsertOne) SetExpiresAt(v time.Time) *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CardServerNonceUpsertOne) UpdateExpiresAt() *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *CardServerNonceUpsertOne) SetConsumedAt(v time.Time) *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *CardServerNonceUpsertOne) UpdateConsumedAt() *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *CardServerNonceUpsertOne) ClearConsumedAt() *CardServerNonceUpsertOne {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *CardServerNonceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CardServerNonceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CardServerNonceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CardServerNonceUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CardServerNonceUpsertOne.ID is not supported by MySQL driver. Use CardServerNonceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CardServerNonceUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CardServerNonceCreateBulk is the builder for creating many CardServerNonce entities in bulk.
type CardServerNonceCreateBulk struct {
	config
	err      error
	builders []*CardServerNonceCreate
	conflict []sql.ConflictOption
}

// Save creates the CardServerNonce entities in the database.
func (csncb *CardServerNonceCreateBulk) Save(ctx context.Context) ([]*CardServerNonce, error) {
	if csncb.err != nil {
		return nil, csncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(csncb.builders))
	nodes := make([]*CardServerNonce, len(csncb.builders))
	mutators := make([]Mutator, len(csncb.builders))
	for i := range csncb.builders {
		func(i int, root context.Context) {
			builder := csncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CardServerNonceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, csncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = csncb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, csncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, csncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (csncb *CardServerNonceCreateBulk) SaveX(ctx context.Context) []*CardServerNonce {
	v, err := csncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (csncb *CardServerNonceCreateBulk) Exec(ctx context.Context) error {
	_, err := csncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csncb *CardServerNonceCreateBulk) ExecX(ctx context.Context) {
	if err := csncb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CardServerNonce.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CardServerNonceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (csncb *CardServerNonceCreateBulk) OnConflict(opts ...sql.ConflictOption) *CardServerNonceUpsertBulk {
	csncb.conflict = opts
	return &CardServerNonceUpsertBulk{
		create: csncb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CardServerNonce.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (csncb *CardServerNonceCreateBulk) OnConflictColumns(columns ...string) *CardServerNonceUpsertBulk {
	csncb.conflict = append(csncb.conflict, sql.ConflictColumns(columns...))
	return &CardServerNonceUpsertBulk{
		create: csncb,
	}
}

// CardServerNonceUpsertBulk is the builder for "upsert"-ing
// a bulk of CardServerNonce nodes.
type CardServerNonceUpsertBulk struct {
	create *CardServerNonceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CardServerNonce.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(cardservernonce.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CardServerNonceUpsertBulk) UpdateNewValues() *CardServerNonceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(cardservernonce.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(cardservernonce.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CardServerNonce.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CardServerNonceUpsertBulk) Ignore() *CardServerNonceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CardServerNonceUpsertBulk) DoNothing() *CardServerNonceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CardServerNonceCreateBulk.OnConflict
// documentation for more info.
func (u *CardServerNonceUpsertBulk) Update(set func(*CardServerNonceUpsert)) *CardServerNonceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CardServerNonceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CardServerNonceUpsertBulk) SetUpdatedAt(v time.Time) *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CardServerNonceUpsertBulk) UpdateUpdatedAt() *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetNonce sets the "nonce" field.
func (u *CardServerNonceUpsertBulk) SetNonce(v []byte) *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *CardServerNonceUpsertBulk) UpdateNonce() *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateNonce()
	})
}

// SetTier sets the "tier" field.
func (u *CardServerNonceUpsertBulk) SetTier(v cardservernonce.Tier) *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *CardServerNonceUpsertBulk) UpdateTier() *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateTier()
	})
}

// SetAmount sets the "amount" field.
func (u *CardServerNonceUpsertBulk) SetAmount(v string) *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CardServerNonceUpsertBulk) UpdateAmount() *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *CardServerNonceUpsertBulk) SetCurrency(v string) *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CardServerNonceUpsertBulk) UpdateCurrency() *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateCurrency()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CardServerNonceUpsertBulk) SetExpiresAt(v time.Time) *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CardServerNonceUpsertBulk) UpdateExpiresAt() *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *CardServerNonceUpsertBulk) SetConsumedAt(v time.Time) *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *CardServerNonceUpsertBulk) UpdateConsumedAt() *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *CardServerNonceUpsertBulk) ClearConsumedAt() *CardServerNonceUpsertBulk {
	return u.Update(func(s *CardServerNonceUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *CardServerNonceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CardServerNonceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CardServerNonceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CardServerNonceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
