// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/usezoracle/rails-sui/ent/lpaccount"
	"github.com/usezoracle/rails-sui/ent/lpledgerentry"
	"github.com/usezoracle/rails-sui/ent/predicate"
	"github.com/usezoracle/rails-sui/ent/user"
)

// LpAccountUpdate is the builder for updating LpAccount entities.
type LpAccountUpdate struct {
	config
	hooks    []Hook
	mutation *LpAccountMutation
}

// Where appends a list predicates to the LpAccountUpdate builder.
func (lau *LpAccountUpdate) Where(ps ...predicate.LpAccount) *LpAccountUpdate {
	lau.mutation.Where(ps...)
	return lau
}

// SetUpdatedAt sets the "updated_at" field.
func (lau *LpAccountUpdate) SetUpdatedAt(t time.Time) *LpAccountUpdate {
	lau.mutation.SetUpdatedAt(t)
	return lau
}

// SetName sets the "name" field.
func (lau *LpAccountUpdate) SetName(s string) *LpAccountUpdate {
	lau.mutation.SetName(s)
	return lau
}

// SetNillableName sets the "name" field if the given value is not nil.
func (lau *LpAccountUpdate) SetNillableName(s *string) *LpAccountUpdate {
	if s != nil {
		lau.SetName(*s)
	}
	return lau
}

// SetEmail sets the "email" field.
func (lau *LpAccountUpdate) SetEmail(s string) *LpAccountUpdate {
	lau.mutation.SetEmail(s)
	return lau
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (lau *LpAccountUpdate) SetNillableEmail(s *string) *LpAccountUpdate {
	if s != nil {
		lau.SetEmail(*s)
	}
	return lau
}

// SetBvnLast4 sets the "bvn_last4" field.
func (lau *LpAccountUpdate) SetBvnLast4(s string) *LpAccountUpdate {
	lau.mutation.SetBvnLast4(s)
	return lau
}

// SetNillableBvnLast4 sets the "bvn_last4" field if the given value is not nil.
func (lau *LpAccountUpdate) SetNillableBvnLast4(s *string) *LpAccountUpdate {
	if s != nil {
		lau.SetBvnLast4(*s)
	}
	return lau
}

// SetAccountReference sets the "account_reference" field.
func (lau *LpAccountUpdate) SetAccountReference(s string) *LpAccountUpdate {
	lau.mutation.SetAccountReference(s)
	return lau
}

// SetNillableAccountReference sets the "account_reference" field if the given value is not nil.
func (lau *LpAccountUpdate) SetNillableAccountReference(s *string) *LpAccountUpdate {
	if s != nil {
		lau.SetAccountReference(*s)
	}
	return lau
}

// SetAccountNumber sets the "account_number" field.
func (lau *LpAccountUpdate) SetAccountNumber(s string) *LpAccountUpdate {
	lau.mutation.SetAccountNumber(s)
	return lau
}

// SetNillableAccountNumber sets the "account_number" field if the given value is not nil.
func (lau *LpAccountUpdate) SetNillableAccountNumber(s *string) *LpAccountUpdate {
	if s != nil {
		lau.SetAccountNumber(*s)
	}
	return lau
}

// SetBankName sets the "bank_name" field.
func (lau *LpAccountUpdate) SetBankName(s string) *LpAccountUpdate {
	lau.mutation.SetBankName(s)
	return lau
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (lau *LpAccountUpdate) SetNillableBankName(s *string) *LpAccountUpdate {
	if s != nil {
		lau.SetBankName(*s)
	}
	return lau
}

// SetBankCode sets the "bank_code" field.
func (lau *LpAccountUpdate) SetBankCode(s string) *LpAccountUpdate {
	lau.mutation.SetBankCode(s)
	return lau
}

// SetNillableBankCode sets the "bank_code" field if the given value is not nil.
func (lau *LpAccountUpdate) SetNillableBankCode(s *string) *LpAccountUpdate {
	if s != nil {
		lau.SetBankCode(*s)
	}
	return lau
}

// SetStatus sets the "status" field.
func (lau *LpAccountUpdate) SetStatus(l lpaccount.Status) *LpAccountUpdate {
	lau.mutation.SetStatus(l)
	return lau
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (lau *LpAccountUpdate) SetNillableStatus(l *lpaccount.Status) *LpAccountUpdate {
	if l != nil {
		lau.SetStatus(*l)
	}
	return lau
}

// SetBalance sets the "balance" field.
func (lau *LpAccountUpdate) SetBalance(d decimal.Decimal) *LpAccountUpdate {
	lau.mutation.ResetBalance()
	lau.mutation.SetBalance(d)
	return lau
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (lau *LpAccountUpdate) SetNillableBalance(d *decimal.Decimal) *LpAccountUpdate {
	if d != nil {
		lau.SetBalance(*d)
	}
	return lau
}

// AddBalance adds d to the "balance" field.
func (lau *LpAccountUpdate) AddBalance(d decimal.Decimal) *LpAccountUpdate {
	lau.mutation.AddBalance(d)
	return lau
}

// SetUserID sets the "user" edge to the User entity by ID.
func (lau *LpAccountUpdate) SetUserID(id uuid.UUID) *LpAccountUpdate {
	lau.mutation.SetUserID(id)
	return lau
}

// SetUser sets the "user" edge to the User entity.
func (lau *LpAccountUpdate) SetUser(u *User) *LpAccountUpdate {
	return lau.SetUserID(u.ID)
}

// AddLedgerEntryIDs adds the "ledger_entries" edge to the LpLedgerEntry entity by IDs.
func (lau *LpAccountUpdate) AddLedgerEntryIDs(ids ...uuid.UUID) *LpAccountUpdate {
	lau.mutation.AddLedgerEntryIDs(ids...)
	return lau
}

// AddLedgerEntries adds the "ledger_entries" edges to the LpLedgerEntry entity.
func (lau *LpAccountUpdate) AddLedgerEntries(l ...*LpLedgerEntry) *LpAccountUpdate {
	ids := make([]uuid.UUID, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return lau.AddLedgerEntryIDs(ids...)
}

// Mutation returns the LpAccountMutation object of the builder.
func (lau *LpAccountUpdate) Mutation() *LpAccountMutation {
	return lau.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (lau *LpAccountUpdate) ClearUser() *LpAccountUpdate {
	lau.mutation.ClearUser()
	return lau
}

// ClearLedgerEntries clears all "ledger_entries" edges to the LpLedgerEntry entity.
func (lau *LpAccountUpdate) ClearLedgerEntries() *LpAccountUpdate {
	lau.mutation.ClearLedgerEntries()
	return lau
}

// RemoveLedgerEntryIDs removes the "ledger_entries" edge to LpLedgerEntry entities by IDs.
func (lau *LpAccountUpdate) RemoveLedgerEntryIDs(ids ...uuid.UUID) *LpAccountUpdate {
	lau.mutation.RemoveLedgerEntryIDs(ids...)
	return lau
}

// RemoveLedgerEntries removes "ledger_entries" edges to LpLedgerEntry entities.
func (lau *LpAccountUpdate) RemoveLedgerEntries(l ...*LpLedgerEntry) *LpAccountUpdate {
	ids := make([]uuid.UUID, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return lau.RemoveLedgerEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lau *LpAccountUpdate) Save(ctx context.Context) (int, error) {
	lau.defaults()
	return withHooks(ctx, lau.sqlSave, lau.mutation, lau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lau *LpAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := lau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lau *LpAccountUpdate) Exec(ctx context.Context) error {
	_, err := lau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lau *LpAccountUpdate) ExecX(ctx context.Context) {
	if err := lau.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lau *LpAccountUpdate) defaults() {
	if _, ok := lau.mutation.UpdatedAt(); !ok {
		v := lpaccount.UpdateDefaultUpdatedAt()
		lau.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lau *LpAccountUpdate) check() error {
	if v, ok := lau.mutation.BvnLast4(); ok {
		if err := lpaccount.BvnLast4Validator(v); err != nil {
			return &ValidationError{Name: "bvn_last4", err: fmt.Errorf(`ent: validator failed for field "LpAccount.bvn_last4": %w`, err)}
		}
	}
	if v, ok := lau.mutation.Status(); ok {
		if err := lpaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LpAccount.status": %w`, err)}
		}
	}
	if lau.mutation.UserCleared() && len(lau.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LpAccount.user"`)
	}
	return nil
}

func (lau *LpAccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := lau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(lpaccount.Table, lpaccount.Columns, sqlgraph.NewFieldSpec(lpaccount.FieldID, field.TypeUUID))
	if ps := lau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lau.mutation.UpdatedAt(); ok {
		_spec.SetField(lpaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := lau.mutation.Name(); ok {
		_spec.SetField(lpaccount.FieldName, field.TypeString, value)
	}
	if value, ok := lau.mutation.Email(); ok {
		_spec.SetField(lpaccount.FieldEmail, field.TypeString, value)
	}
	if value, ok := lau.mutation.BvnLast4(); ok {
		_spec.SetField(lpaccount.FieldBvnLast4, field.TypeString, value)
	}
	if value, ok := lau.mutation.AccountReference(); ok {
		_spec.SetField(lpaccount.FieldAccountReference, field.TypeString, value)
	}
	if value, ok := lau.mutation.AccountNumber(); ok {
		_spec.SetField(lpaccount.FieldAccountNumber, field.TypeString, value)
	}
	if value, ok := lau.mutation.BankName(); ok {
		_spec.SetField(lpaccount.FieldBankName, field.TypeString, value)
	}
	if value, ok := lau.mutation.BankCode(); ok {
		_spec.SetField(lpaccount.FieldBankCode, field.TypeString, value)
	}
	if value, ok := lau.mutation.Status(); ok {
		_spec.SetField(lpaccount.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := lau.mutation.Balance(); ok {
		_spec.SetField(lpaccount.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := lau.mutation.AddedBalance(); ok {
		_spec.AddField(lpaccount.FieldBalance, field.TypeFloat64, value)
	}
	if lau.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   lpaccount.UserTable,
			Columns: []string{lpaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lau.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   lpaccount.UserTable,
			Columns: []string{lpaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lau.mutation.LedgerEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lpaccount.LedgerEntriesTable,
			Columns: []string{lpaccount.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lpledgerentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lau.mutation.RemovedLedgerEntriesIDs(); len(nodes) > 0 && !lau.mutation.LedgerEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lpaccount.LedgerEntriesTable,
			Columns: []string{lpaccount.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lpledgerentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lau.mutation.LedgerEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lpaccount.LedgerEntriesTable,
			Columns: []string{lpaccount.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lpledgerentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lpaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lau.mutation.done = true
	return n, nil
}

// LpAccountUpdateOne is the builder for updating a single LpAccount entity.
type LpAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LpAccountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (lauo *LpAccountUpdateOne) SetUpdatedAt(t time.Time) *LpAccountUpdateOne {
	lauo.mutation.SetUpdatedAt(t)
	return lauo
}

// SetName sets the "name" field.
func (lauo *LpAccountUpdateOne) SetName(s string) *LpAccountUpdateOne {
	lauo.mutation.SetName(s)
	return lauo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (lauo *LpAccountUpdateOne) SetNillableName(s *string) *LpAccountUpdateOne {
	if s != nil {
		lauo.SetName(*s)
	}
	return lauo
}

// SetEmail sets the "email" field.
func (lauo *LpAccountUpdateOne) SetEmail(s string) *LpAccountUpdateOne {
	lauo.mutation.SetEmail(s)
	return lauo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (lauo *LpAccountUpdateOne) SetNillableEmail(s *string) *LpAccountUpdateOne {
	if s != nil {
		lauo.SetEmail(*s)
	}
	return lauo
}

// SetBvnLast4 sets the "bvn_last4" field.
func (lauo *LpAccountUpdateOne) SetBvnLast4(s string) *LpAccountUpdateOne {
	lauo.mutation.SetBvnLast4(s)
	return lauo
}

// SetNillableBvnLast4 sets the "bvn_last4" field if the given value is not nil.
func (lauo *LpAccountUpdateOne) SetNillableBvnLast4(s *string) *LpAccountUpdateOne {
	if s != nil {
		lauo.SetBvnLast4(*s)
	}
	return lauo
}

// SetAccountReference sets the "account_reference" field.
func (lauo *LpAccountUpdateOne) SetAccountReference(s string) *LpAccountUpdateOne {
	lauo.mutation.SetAccountReference(s)
	return lauo
}

// SetNillableAccountReference sets the "account_reference" field if the given value is not nil.
func (lauo *LpAccountUpdateOne) SetNillableAccountReference(s *string) *LpAccountUpdateOne {
	if s != nil {
		lauo.SetAccountReference(*s)
	}
	return lauo
}

// SetAccountNumber sets the "account_number" field.
func (lauo *LpAccountUpdateOne) SetAccountNumber(s string) *LpAccountUpdateOne {
	lauo.mutation.SetAccountNumber(s)
	return lauo
}

// SetNillableAccountNumber sets the "account_number" field if the given value is not nil.
func (lauo *LpAccountUpdateOne) SetNillableAccountNumber(s *string) *LpAccountUpdateOne {
	if s != nil {
		lauo.SetAccountNumber(*s)
	}
	return lauo
}

// SetBankName sets the "bank_name" field.
func (lauo *LpAccountUpdateOne) SetBankName(s string) *LpAccountUpdateOne {
	lauo.mutation.SetBankName(s)
	return lauo
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (lauo *LpAccountUpdateOne) SetNillableBankName(s *string) *LpAccountUpdateOne {
	if s != nil {
		lauo.SetBankName(*s)
	}
	return lauo
}

// SetBankCode sets the "bank_code" field.
func (lauo *LpAccountUpdateOne) SetBankCode(s string) *LpAccountUpdateOne {
	lauo.mutation.SetBankCode(s)
	return lauo
}

// SetNillableBankCode sets the "bank_code" field if the given value is not nil.
func (lauo *LpAccountUpdateOne) SetNillableBankCode(s *string) *LpAccountUpdateOne {
	if s != nil {
		lauo.SetBankCode(*s)
	}
	return lauo
}

// SetStatus sets the "status" field.
func (lauo *LpAccountUpdateOne) SetStatus(l lpaccount.Status) *LpAccountUpdateOne {
	lauo.mutation.SetStatus(l)
	return lauo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (lauo *LpAccountUpdateOne) SetNillableStatus(l *lpaccount.Status) *LpAccountUpdateOne {
	if l != nil {
		lauo.SetStatus(*l)
	}
	return lauo
}

// SetBalance sets the "balance" field.
func (lauo *LpAccountUpdateOne) SetBalance(d decimal.Decimal) *LpAccountUpdateOne {
	lauo.mutation.ResetBalance()
	lauo.mutation.SetBalance(d)
	return lauo
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (lauo *LpAccountUpdateOne) SetNillableBalance(d *decimal.Decimal) *LpAccountUpdateOne {
	if d != nil {
		lauo.SetBalance(*d)
	}
	return lauo
}

// AddBalance adds d to the "balance" field.
func (lauo *LpAccountUpdateOne) AddBalance(d decimal.Decimal) *LpAccountUpdateOne {
	lauo.mutation.AddBalance(d)
	return lauo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (lauo *LpAccountUpdateOne) SetUserID(id uuid.UUID) *LpAccountUpdateOne {
	lauo.mutation.SetUserID(id)
	return lauo
}

// SetUser sets the "user" edge to the User entity.
func (lauo *LpAccountUpdateOne) SetUser(u *User) *LpAccountUpdateOne {
	return lauo.SetUserID(u.ID)
}

// AddLedgerEntryIDs adds the "ledger_entries" edge to the LpLedgerEntry entity by IDs.
func (lauo *LpAccountUpdateOne) AddLedgerEntryIDs(ids ...uuid.UUID) *LpAccountUpdateOne {
	lauo.mutation.AddLedgerEntryIDs(ids...)
	return lauo
}

// AddLedgerEntries adds the "ledger_entries" edges to the LpLedgerEntry entity.
func (lauo *LpAccountUpdateOne) AddLedgerEntries(l ...*LpLedgerEntry) *LpAccountUpdateOne {
	ids := make([]uuid.UUID, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return lauo.AddLedgerEntryIDs(ids...)
}

// Mutation returns the LpAccountMutation object of the builder.
func (lauo *LpAccountUpdateOne) Mutation() *LpAccountMutation {
	return lauo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (lauo *LpAccountUpdateOne) ClearUser() *LpAccountUpdateOne {
	lauo.mutation.ClearUser()
	return lauo
}

// ClearLedgerEntries clears all "ledger_entries" edges to the LpLedgerEntry entity.
func (lauo *LpAccountUpdateOne) ClearLedgerEntries() *LpAccountUpdateOne {
	lauo.mutation.ClearLedgerEntries()
	return lauo
}

// RemoveLedgerEntryIDs removes the "ledger_entries" edge to LpLedgerEntry entities by IDs.
func (lauo *LpAccountUpdateOne) RemoveLedgerEntryIDs(ids ...uuid.UUID) *LpAccountUpdateOne {
	lauo.mutation.RemoveLedgerEntryIDs(ids...)
	return lauo
}

// RemoveLedgerEntries removes "ledger_entries" edges to LpLedgerEntry entities.
func (lauo *LpAccountUpdateOne) RemoveLedgerEntries(l ...*LpLedgerEntry) *LpAccountUpdateOne {
	ids := make([]uuid.UUID, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return lauo.RemoveLedgerEntryIDs(ids...)
}

// Where appends a list predicates to the LpAccountUpdate builder.
func (lauo *LpAccountUpdateOne) Where(ps ...predicate.LpAccount) *LpAccountUpdateOne {
	lauo.mutation.Where(ps...)
	return lauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (lauo *LpAccountUpdateOne) Select(field string, fields ...string) *LpAccountUpdateOne {
	lauo.fields = append([]string{field}, fields...)
	return lauo
}

// Save executes the query and returns the updated LpAccount entity.
func (lauo *LpAccountUpdateOne) Save(ctx context.Context) (*LpAccount, error) {
	lauo.defaults()
	return withHooks(ctx, lauo.sqlSave, lauo.mutation, lauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lauo *LpAccountUpdateOne) SaveX(ctx context.Context) *LpAccount {
	node, err := lauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (lauo *LpAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := lauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lauo *LpAccountUpdateOne) ExecX(ctx context.Context) {
	if err := lauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lauo *LpAccountUpdateOne) defaults() {
	if _, ok := lauo.mutation.UpdatedAt(); !ok {
		v := lpaccount.UpdateDefaultUpdatedAt()
		lauo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lauo *LpAccountUpdateOne) check() error {
	if v, ok := lauo.mutation.BvnLast4(); ok {
		if err := lpaccount.BvnLast4Validator(v); err != nil {
			return &ValidationError{Name: "bvn_last4", err: fmt.Errorf(`ent: validator failed for field "LpAccount.bvn_last4": %w`, err)}
		}
	}
	if v, ok := lauo.mutation.Status(); ok {
		if err := lpaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LpAccount.status": %w`, err)}
		}
	}
	if lauo.mutation.UserCleared() && len(lauo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LpAccount.user"`)
	}
	return nil
}

func (lauo *LpAccountUpdateOne) sqlSave(ctx context.Context) (_node *LpAccount, err error) {
	if err := lauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lpaccount.Table, lpaccount.Columns, sqlgraph.NewFieldSpec(lpaccount.FieldID, field.TypeUUID))
	id, ok := lauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LpAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := lauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lpaccount.FieldID)
		for _, f := range fields {
			if !lpaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lpaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := lauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lauo.mutation.UpdatedAt(); ok {
		_spec.SetField(lpaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := lauo.mutation.Name(); ok {
		_spec.SetField(lpaccount.FieldName, field.TypeString, value)
	}
	if value, ok := lauo.mutation.Email(); ok {
		_spec.SetField(lpaccount.FieldEmail, field.TypeString, value)
	}
	if value, ok := lauo.mutation.BvnLast4(); ok {
		_spec.SetField(lpaccount.FieldBvnLast4, field.TypeString, value)
	}
	if value, ok := lauo.mutation.AccountReference(); ok {
		_spec.SetField(lpaccount.FieldAccountReference, field.TypeString, value)
	}
	if value, ok := lauo.mutation.AccountNumber(); ok {
		_spec.SetField(lpaccount.FieldAccountNumber, field.TypeString, value)
	}
	if value, ok := lauo.mutation.BankName(); ok {
		_spec.SetField(lpaccount.FieldBankName, field.TypeString, value)
	}
	if value, ok := lauo.mutation.BankCode(); ok {
		_spec.SetField(lpaccount.FieldBankCode, field.TypeString, value)
	}
	if value, ok := lauo.mutation.Status(); ok {
		_spec.SetField(lpaccount.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := lauo.mutation.Balance(); ok {
		_spec.SetField(lpaccount.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := lauo.mutation.AddedBalance(); ok {
		_spec.AddField(lpaccount.FieldBalance, field.TypeFloat64, value)
	}
	if lauo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   lpaccount.UserTable,
			Columns: []string{lpaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lauo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   lpaccount.UserTable,
			Columns: []string{lpaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lauo.mutation.LedgerEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lpaccount.LedgerEntriesTable,
			Columns: []string{lpaccount.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lpledgerentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lauo.mutation.RemovedLedgerEntriesIDs(); len(nodes) > 0 && !lauo.mutation.LedgerEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lpaccount.LedgerEntriesTable,
			Columns: []string{lpaccount.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lpledgerentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lauo.mutation.LedgerEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lpaccount.LedgerEntriesTable,
			Columns: []string{lpaccount.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lpledgerentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LpAccount{config: lauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, lauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lpaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	lauo.mutation.done = true
	return _node, nil
}
