// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/usezoracle/rails-sui/ent/merchantbankaccount"
	"github.com/usezoracle/rails-sui/ent/predicate"
)

// MerchantBankAccountDelete is the builder for deleting a MerchantBankAccount entity.
type MerchantBankAccountDelete struct {
	config
	hooks    []Hook
	mutation *MerchantBankAccountMutation
}

// Where appends a list predicates to the MerchantBankAccountDelete builder.
func (mbad *MerchantBankAccountDelete) Where(ps ...predicate.MerchantBankAccount) *MerchantBankAccountDelete {
	mbad.mutation.Where(ps...)
	return mbad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mbad *MerchantBankAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mbad.sqlExec, mbad.mutation, mbad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mbad *MerchantBankAccountDelete) ExecX(ctx context.Context) int {
	n, err := mbad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mbad *MerchantBankAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(merchantbankaccount.Table, sqlgraph.NewFieldSpec(merchantbankaccount.FieldID, field.TypeUUID))
	if ps := mbad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mbad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mbad.mutation.done = true
	return affected, err
}

// MerchantBankAccountDeleteOne is the builder for deleting a single MerchantBankAccount entity.
type MerchantBankAccountDeleteOne struct {
	mbad *MerchantBankAccountDelete
}

// Where appends a list predicates to the MerchantBankAccountDelete builder.
func (mbado *MerchantBankAccountDeleteOne) Where(ps ...predicate.MerchantBankAccount) *MerchantBankAccountDeleteOne {
	mbado.mbad.mutation.Where(ps...)
	return mbado
}

// Exec executes the deletion query.
func (mbado *MerchantBankAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := mbado.mbad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{merchantbankaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mbado *MerchantBankAccountDeleteOne) ExecX(ctx context.Context) {
	if err := mbado.Exec(ctx); err != nil {
		panic(err)
	}
}
