// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/usezoracle/rails-sui/ent/paymentorder"
	"github.com/usezoracle/rails-sui/ent/paymentorderrecipient"
)

// PaymentOrderRecipientCreate is the builder for creating a PaymentOrderRecipient entity.
type PaymentOrderRecipientCreate struct {
	config
	mutation *PaymentOrderRecipientMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInstitution sets the "institution" field.
func (porc *PaymentOrderRecipientCreate) SetInstitution(s string) *PaymentOrderRecipientCreate {
	porc.mutation.SetInstitution(s)
	return porc
}

// SetAccountIdentifier sets the "account_identifier" field.
func (porc *PaymentOrderRecipientCreate) SetAccountIdentifier(s string) *PaymentOrderRecipientCreate {
	porc.mutation.SetAccountIdentifier(s)
	return porc
}

// SetAccountName sets the "account_name" field.
func (porc *PaymentOrderRecipientCreate) SetAccountName(s string) *PaymentOrderRecipientCreate {
	porc.mutation.SetAccountName(s)
	return porc
}

// SetMemo sets the "memo" field.
func (porc *PaymentOrderRecipientCreate) SetMemo(s string) *PaymentOrderRecipientCreate {
	porc.mutation.SetMemo(s)
	return porc
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (porc *PaymentOrderRecipientCreate) SetNillableMemo(s *string) *PaymentOrderRecipientCreate {
	if s != nil {
		porc.SetMemo(*s)
	}
	return porc
}

// SetProviderID sets the "provider_id" field.
func (porc *PaymentOrderRecipientCreate) SetProviderID(s string) *PaymentOrderRecipientCreate {
	porc.mutation.SetProviderID(s)
	return porc
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (porc *PaymentOrderRecipientCreate) SetNillableProviderID(s *string) *PaymentOrderRecipientCreate {
	if s != nil {
		porc.SetProviderID(*s)
	}
	return porc
}

// SetPaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID.
func (porc *PaymentOrderRecipientCreate) SetPaymentOrderID(id uuid.UUID) *PaymentOrderRecipientCreate {
	porc.mutation.SetPaymentOrderID(id)
	return porc
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (porc *PaymentOrderRecipientCreate) SetPaymentOrder(p *PaymentOrder) *PaymentOrderRecipientCreate {
	return porc.SetPaymentOrderID(p.ID)
}

// Mutation returns the PaymentOrderRecipientMutation object of the builder.
func (porc *PaymentOrderRecipientCreate) Mutation() *PaymentOrderRecipientMutation {
	return porc.mutation
}

// Save creates the PaymentOrderRecipient in the database.
func (porc *PaymentOrderRecipientCreate) Save(ctx context.Context) (*PaymentOrderRecipient, error) {
	return withHooks(ctx, porc.sqlSave, porc.mutation, porc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (porc *PaymentOrderRecipientCreate) SaveX(ctx context.Context) *PaymentOrderRecipient {
	v, err := porc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (porc *PaymentOrderRecipientCreate) Exec(ctx context.Context) error {
	_, err := porc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (porc *PaymentOrderRecipientCreate) ExecX(ctx context.Context) {
	if err := porc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (porc *PaymentOrderRecipientCreate) check() error {
	if _, ok := porc.mutation.Institution(); !ok {
		return &ValidationError{Name: "institution", err: errors.New(`ent: missing required field "PaymentOrderRecipient.institution"`)}
	}
	if _, ok := porc.mutation.AccountIdentifier(); !ok {
		return &ValidationError{Name: "account_identifier", err: errors.New(`ent: missing required field "PaymentOrderRecipient.account_identifier"`)}
	}
	if _, ok := porc.mutation.AccountName(); !ok {
		return &ValidationError{Name: "account_name", err: errors.New(`ent: missing required field "PaymentOrderRecipient.account_name"`)}
	}
	if len(porc.mutation.PaymentOrderIDs()) == 0 {
		return &ValidationError{Name: "payment_order", err: errors.New(`ent: missing required edge "PaymentOrderRecipient.payment_order"`)}
	}
	return nil
}

func (porc *PaymentOrderRecipientCreate) sqlSave(ctx context.Context) (*PaymentOrderRecipient, error) {
	if err := porc.check(); err != nil {
		return nil, err
	}
	_node, _spec := porc.createSpec()
	if err := sqlgraph.CreateNode(ctx, porc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	porc.mutation.id = &_node.ID
	porc.mutation.done = true
	return _node, nil
}

func (porc *PaymentOrderRecipientCreate) createSpec() (*PaymentOrderRecipient, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentOrderRecipient{config: porc.config}
		_spec = sqlgraph.NewCreateSpec(paymentorderrecipient.Table, sqlgraph.NewFieldSpec(paymentorderrecipient.FieldID, field.TypeInt))
	)
	_spec.OnConflict = porc.conflict
	if value, ok := porc.mutation.Institution(); ok {
		_spec.SetField(paymentorderrecipient.FieldInstitution, field.TypeString, value)
		_node.Institution = value
	}
	if value, ok := porc.mutation.AccountIdentifier(); ok {
		_spec.SetField(paymentorderrecipient.FieldAccountIdentifier, field.TypeString, value)
		_node.AccountIdentifier = value
	}
	if value, ok := porc.mutation.AccountName(); ok {
		_spec.SetField(paymentorderrecipient.FieldAccountName, field.TypeString, value)
		_node.AccountName = value
	}
	if value, ok := porc.mutation.Memo(); ok {
		_spec.SetField(paymentorderrecipient.FieldMemo, field.TypeString, value)
		_node.Memo = value
	}
	if value, ok := porc.mutation.ProviderID(); ok {
		_spec.SetField(paymentorderrecipient.FieldProviderID, field.TypeString, value)
		_node.ProviderID = value
	}
	if nodes := porc.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentorderrecipient.PaymentOrderTable,
			Columns: []string{paymentorderrecipient.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.payment_order_recipient = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrderRecipient.Create().
//		SetInstitution(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderRecipientUpsert) {
//			SetInstitution(v+v).
//		}).
//		Exec(ctx)
func (porc *PaymentOrderRecipientCreate) OnConflict(opts ...sql.ConflictOption) *PaymentOrderRecipientUpsertOne {
	porc.conflict = opts
	return &PaymentOrderRecipientUpsertOne{
		create: porc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrderRecipient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (porc *PaymentOrderRecipientCreate) OnConflictColumns(columns ...string) *PaymentOrderRecipientUpsertOne {
	porc.conflict = append(porc.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderRecipientUpsertOne{
		create: porc,
	}
}

type (
	// PaymentOrderRecipientUpsertOne is the builder for "upsert"-ing
	//  one PaymentOrderRecipient node.
	PaymentOrderRecipientUpsertOne struct {
		create *PaymentOrderRecipientCreate
	}

	// PaymentOrderRecipientUpsert is the "OnConflict" setter.
	PaymentOrderRecipientUpsert struct {
		*sql.UpdateSet
	}
)

// SetInstitution sets the "institution" field.
func (u *PaymentOrderRecipientUpsert) SetInstitution(v string) *PaymentOrderRecipientUpsert {
	u.Set(paymentorderrecipient.FieldInstitution, v)
	return u
}

// UpdateInstitution sets the "institution" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsert) UpdateInstitution() *PaymentOrderRecipientUpsert {
	u.SetExcluded(paymentorderrecipient.FieldInstitution)
	return u
}

// SetAccountIdentifier sets the "account_identifier" field.
func (u *PaymentOrderRecipientUpsert) SetAccountIdentifier(v string) *PaymentOrderRecipientUpsert {
	u.Set(paymentorderrecipient.FieldAccountIdentifier, v)
	return u
}

// UpdateAccountIdentifier sets the "account_identifier" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsert) UpdateAccountIdentifier() *PaymentOrderRecipientUpsert {
	u.SetExcluded(paymentorderrecipient.FieldAccountIdentifier)
	return u
}

// SetAccountName sets the "account_name" field.
func (u *PaymentOrderRecipientUpsert) SetAccountName(v string) *PaymentOrderRecipientUpsert {
	u.Set(paymentorderrecipient.FieldAccountName, v)
	return u
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsert) UpdateAccountName() *PaymentOrderRecipientUpsert {
	u.SetExcluded(paymentorderrecipient.FieldAccountName)
	return u
}

// SetMemo sets the "memo" field.
func (u *PaymentOrderRecipientUpsert) SetMemo(v string) *PaymentOrderRecipientUpsert {
	u.Set(paymentorderrecipient.FieldMemo, v)
	return u
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsert) UpdateMemo() *PaymentOrderRecipientUpsert {
	u.SetExcluded(paymentorderrecipient.FieldMemo)
	return u
}

// ClearMemo clears the value of the "memo" field.
func (u *PaymentOrderRecipientUpsert) ClearMemo() *PaymentOrderRecipientUpsert {
	u.SetNull(paymentorderrecipient.FieldMemo)
	return u
}

// SetProviderID sets the "provider_id" field.
func (u *PaymentOrderRecipientUpsert) SetProviderID(v string) *PaymentOrderRecipientUpsert {
	u.Set(paymentorderrecipient.FieldProviderID, v)
	return u
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsert) UpdateProviderID() *PaymentOrderRecipientUpsert {
	u.SetExcluded(paymentorderrecipient.FieldProviderID)
	return u
}

// ClearProviderID clears the value of the "provider_id" field.
func (u *PaymentOrderRecipientUpsert) ClearProviderID() *PaymentOrderRecipientUpsert {
	u.SetNull(paymentorderrecipient.FieldProviderID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentOrderRecipient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentOrderRecipientUpsertOne) UpdateNewValues() *PaymentOrderRecipientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrderRecipient.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentOrderRecipientUpsertOne) Ignore() *PaymentOrderRecipientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderRecipientUpsertOne) DoNothing() *PaymentOrderRecipientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderRecipientCreate.OnConflict
// documentation for more info.
func (u *PaymentOrderRecipientUpsertOne) Update(set func(*PaymentOrderRecipientUpsert)) *PaymentOrderRecipientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderRecipientUpsert{UpdateSet: update})
	}))
	return u
}

// SetInstitution sets the "institution" field.
func (u *PaymentOrderRecipientUpsertOne) SetInstitution(v string) *PaymentOrderRecipientUpsertOne {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.SetInstitution(v)
	})
}

// UpdateInstitution sets the "institution" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsertOne) UpdateInstitution() *PaymentOrderRecipientUpsertOne {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.UpdateInstitution()
	})
}

// SetAccountIdentifier sets the "account_identifier" field.
func (u *PaymentOrderRecipientUpsertOne) SetAccountIdentifier(v string) *PaymentOrderRecipientUpsertOne {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.SetAccountIdentifier(v)
	})
}

// UpdateAccountIdentifier sets the "account_identifier" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsertOne) UpdateAccountIdentifier() *PaymentOrderRecipientUpsertOne {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.UpdateAccountIdentifier()
	})
}

// SetAccountName sets the "account_name" field.
func (u *PaymentOrderRecipientUpsertOne) SetAccountName(v string) *PaymentOrderRecipientUpsertOne {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.SetAccountName(v)
	})
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsertOne) UpdateAccountName() *PaymentOrderRecipientUpsertOne {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.UpdateAccountName()
	})
}

// SetMemo sets the "memo" field.
func (u *PaymentOrderRecipientUpsertOne) SetMemo(v string) *PaymentOrderRecipientUpsertOne {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.SetMemo(v)
	})
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsertOne) UpdateMemo() *PaymentOrderRecipientUpsertOne {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.UpdateMemo()
	})
}

// ClearMemo clears the value of the "memo" field.
func (u *PaymentOrderRecipientUpsertOne) ClearMemo() *PaymentOrderRecipientUpsertOne {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.ClearMemo()
	})
}

// SetProviderID sets the "provider_id" field.
func (u *PaymentOrderRecipientUpsertOne) SetProviderID(v string) *PaymentOrderRecipientUpsertOne {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.SetProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsertOne) UpdateProviderID() *PaymentOrderRecipientUpsertOne {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.UpdateProviderID()
	})
}

// ClearProviderID clears the value of the "provider_id" field.
func (u *PaymentOrderRecipientUpsertOne) ClearProviderID() *PaymentOrderRecipientUpsertOne {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.ClearProviderID()
	})
}

// Exec executes the query.
func (u *PaymentOrderRecipientUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderRecipientCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderRecipientUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentOrderRecipientUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentOrderRecipientUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentOrderRecipientCreateBulk is the builder for creating many PaymentOrderRecipient entities in bulk.
type PaymentOrderRecipientCreateBulk struct {
	config
	err      error
	builders []*PaymentOrderRecipientCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentOrderRecipient entities in the database.
func (porcb *PaymentOrderRecipientCreateBulk) Save(ctx context.Context) ([]*PaymentOrderRecipient, error) {
	if porcb.err != nil {
		return nil, porcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(porcb.builders))
	nodes := make([]*PaymentOrderRecipient, len(porcb.builders))
	mutators := make([]Mutator, len(porcb.builders))
	for i := range porcb.builders {
		func(i int, root context.Context) {
			builder := porcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentOrderRecipientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, porcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = porcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, porcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, porcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (porcb *PaymentOrderRecipientCreateBulk) SaveX(ctx context.Context) []*PaymentOrderRecipient {
	v, err := porcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (porcb *PaymentOrderRecipientCreateBulk) Exec(ctx context.Context) error {
	_, err := porcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (porcb *PaymentOrderRecipientCreateBulk) ExecX(ctx context.Context) {
	if err := porcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrderRecipient.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderRecipientUpsert) {
//			SetInstitution(v+v).
//		}).
//		Exec(ctx)
func (porcb *PaymentOrderRecipientCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentOrderRecipientUpsertBulk {
	porcb.conflict = opts
	return &PaymentOrderRecipientUpsertBulk{
		create: porcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrderRecipient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (porcb *PaymentOrderRecipientCreateBulk) OnConflictColumns(columns ...string) *PaymentOrderRecipientUpsertBulk {
	porcb.conflict = append(porcb.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderRecipientUpsertBulk{
		create: porcb,
	}
}

// PaymentOrderRecipientUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentOrderRecipient nodes.
type PaymentOrderRecipientUpsertBulk struct {
	create *PaymentOrderRecipientCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentOrderRecipient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentOrderRecipientUpsertBulk) UpdateNewValues() *PaymentOrderRecipientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrderRecipient.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentOrderRecipientUpsertBulk) Ignore() *PaymentOrderRecipientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderRecipientUpsertBulk) DoNothing() *PaymentOrderRecipientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderRecipientCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentOrderRecipientUpsertBulk) Update(set func(*PaymentOrderRecipientUpsert)) *PaymentOrderRecipientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderRecipientUpsert{UpdateSet: update})
	}))
	return u
}

// SetInstitution sets the "institution" field.
func (u *PaymentOrderRecipientUpsertBulk) SetInstitution(v string) *PaymentOrderRecipientUpsertBulk {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.SetInstitution(v)
	})
}

// UpdateInstitution sets the "institution" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsertBulk) UpdateInstitution() *PaymentOrderRecipientUpsertBulk {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.UpdateInstitution()
	})
}

// SetAccountIdentifier sets the "account_identifier" field.
func (u *PaymentOrderRecipientUpsertBulk) SetAccountIdentifier(v string) *PaymentOrderRecipientUpsertBulk {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.SetAccountIdentifier(v)
	})
}

// UpdateAccountIdentifier sets the "account_identifier" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsertBulk) UpdateAccountIdentifier() *PaymentOrderRecipientUpsertBulk {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.UpdateAccountIdentifier()
	})
}

// SetAccountName sets the "account_name" field.
func (u *PaymentOrderRecipientUpsertBulk) SetAccountName(v string) *PaymentOrderRecipientUpsertBulk {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.SetAccountName(v)
	})
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsertBulk) UpdateAccountName() *PaymentOrderRecipientUpsertBulk {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.UpdateAccountName()
	})
}

// SetMemo sets the "memo" field.
func (u *PaymentOrderRecipientUpsertBulk) SetMemo(v string) *PaymentOrderRecipientUpsertBulk {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.SetMemo(v)
	})
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsertBulk) UpdateMemo() *PaymentOrderRecipientUpsertBulk {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.UpdateMemo()
	})
}

// ClearMemo clears the value of the "memo" field.
func (u *PaymentOrderRecipientUpsertBulk) ClearMemo() *PaymentOrderRecipientUpsertBulk {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.ClearMemo()
	})
}

// SetProviderID sets the "provider_id" field.
func (u *PaymentOrderRecipientUpsertBulk) SetProviderID(v string) *PaymentOrderRecipientUpsertBulk {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.SetProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *PaymentOrderRecipientUpsertBulk) UpdateProviderID() *PaymentOrderRecipientUpsertBulk {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.UpdateProviderID()
	})
}

// ClearProviderID clears the value of the "provider_id" field.
func (u *PaymentOrderRecipientUpsertBulk) ClearProviderID() *PaymentOrderRecipientUpsertBulk {
	return u.Update(func(s *PaymentOrderRecipientUpsert) {
		s.ClearProviderID()
	})
}

// Exec executes the query.
func (u *PaymentOrderRecipientUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentOrderRecipientCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderRecipientCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderRecipientUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
