-- Create "institutions" table
CREATE TABLE "institutions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 77309411328), "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'bank', "fiat_currency_institutions" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "institutions_fiat_currencies_institutions" FOREIGN KEY ("fiat_currency_institutions") REFERENCES "fiat_currencies" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "institutions_code_key" to table: "institutions"
CREATE UNIQUE INDEX "institutions_code_key" ON "institutions" ("code");
-- Add pk ranges for ('institutions') tables
INSERT INTO "ent_types" ("type") VALUES ('institutions');
